build:
  environment:
    php:
      version: 7.4.0
  tests:
    override:
      -
        command: 'vendor/bin/phpunit --coverage-clover=coverage.xml'
        coverage:
          file: 'coverage.xml'
          format: 'php-clover'
